POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "agus@gmail.com",
  "password": "aku mau kamu"
}

###
POST {{host}}/auth/register
Content-Type: application/json

{
  "fistName": "Agus",
  "lastName": "Prayogi",
  "email": "agus@gmail.com",
  "password": "aku mau kamu"
}