PUT http://localhost:5199/api/food/001313-313-4141-4141
Content-Type: application/json

{
    "Name": "Apel",
    "Description": "Buah yang segar",
    "Price": 1000,
    "Stock": 10,
    "Tags": [
        "Buah"
    ],
    "ImageUrl": "X-Http-Method-Override"
}