PUT http://localhost:5199/api/Food/ae2ab217-9f4d-4d80-8b23-fe2b86c768e2
Content-Type: application/json

{
    "Name": "Apel Manis",
    "Description": "Buah yang segar",
    "Price": 1000,
    "Stock": 10,
    "Tags": [
        "Buah"
    ],
    "ImageUrl": "X-Http-Method-Override"
}