@id=3823e6d0-b31f-4f44-a666-9fe1f0e52b5e
PUT http://localhost:5199/api/Food/{{id}}
Content-Type: application/json

{
    "Name": "Apel Manis",
    "Description": "Buah yang segar",
    "Price": 1000,
    "Stock": 10,
    "Tags": [
        "Buah"
    ],
    "ImageUrl": "X-Http-Method-Override"
}